@extends('layouts.app')

@section('title', 'Privacy Policy | WivorPhotos')
@section('meta-description', 'How WivorPhotos handles customer, photographer, payment, event-photo, and recognition data.')

@section('content')
    <main class="container py-5">
        <div class="row justify-content-center">
            <article class="col-lg-8">
                <h1 class="mb-3">Privacy Policy</h1>
                <p class="text-muted fw-semibold">Last updated: September 12, 2026</p>

                <div class="card border-0 shadow-sm mt-4">
                    <div class="card-body p-4 p-md-5">
                        <p>WivorPhotos operates an event-photography marketplace where visitors can browse event galleries, find photographs, and purchase digital JPEG files without creating a customer account. This policy explains the information processed through the current service.</p>

                        <h2 class="h4 mt-4">Information we process</h2>
                        <ul>
                            <li><strong>Browsing and cart information:</strong> event and photo requests, bib-number searches, selected-photo cart data, session identifiers, and related security and operational log information generated by service functions.</li>
                            <li><strong>Orders and support:</strong> order numbers, purchased items, amounts, payment and fulfillment status, download access records, and contact information supplied through Stripe, email delivery, support, or photo-removal requests.</li>
                            <li><strong>Photographer information:</strong> account and application details, contact and portfolio information, event assignments, uploaded photographs, sales and commission records, and Stripe Connect onboarding or payout-status information.</li>
                        </ul>

                        <h2 class="h4 mt-4">Payments, email, and storage providers</h2>
                        <p>Stripe hosts checkout and processes payment information. WivorPhotos receives the information needed to identify and fulfill an order, but the WivorPhotos checkout flow does not collect full card details. Email providers deliver application messages and order receipts. Event photographs and their generated previews are stored in private object storage configured through Amazon S3.</p>

                        <h2 class="h4 mt-4">Event-photo and bib processing</h2>
                        <p>Photographers upload event photographs for processing, display, sale, and delivery. WivorPhotos creates watermarked previews and thumbnails. Amazon Rekognition may analyze an uploaded event photograph for visible bib numbers; detected number and confidence data may be saved with that photograph to support bib-number search.</p>

                        <h2 class="h4 mt-4">Face matching</h2>
                        <p>When face search is enabled, published event photographs may be processed by Amazon Rekognition. Facial features found in those photographs may be represented as face metadata in an event-specific Rekognition collection and associated with the photograph's WivorPhotos identifier. This is separate from the voluntary selfie-search flow.</p>
                        <p>A visitor who chooses selfie search uploads a JPEG or PNG image with consent. WivorPhotos reads that temporary request upload into memory and sends the image bytes to Amazon Rekognition to search the selected event collection. WivorPhotos does not intentionally save the search selfie to Amazon S3, its database, the visitor's session, or a queue payload. The temporary request ends after the search response. Amazon processes the image as WivorPhotos' service provider under Amazon's applicable service terms.</p>
                        <p>When a photograph is unpublished, removed, or expires through the current retention process, WivorPhotos queues deletion of its associated face metadata from the event collection. Operational retries or provider availability can affect when that cleanup completes.</p>

                        <h2 class="h4 mt-4">How information is used and shared</h2>
                        <p>WivorPhotos uses this information to operate galleries and search, process and deliver purchases, review photographers, report sales and payout status, respond to support and removal requests, secure and troubleshoot the service, and comply with applicable obligations. Information is shared with service providers such as Amazon Web Services, Stripe, and email-delivery providers only as needed for those functions, and may also be disclosed when required by law or to protect the service and its users.</p>

                        <h2 class="h4 mt-4">Retention and deletion</h2>
                        <p>Cart information is associated with the current browser session. Download access is time-limited, and the order page shows its expiration date. Event media is subject to gallery expiration, purchase-protection periods, administrative holds, removal review, and scheduled cleanup. Order, application, payout, removal-request, and operational records may be retained for support, security, accounting, dispute, and compliance purposes.</p>

                        <h2 class="h4 mt-4">Choices and contact</h2>
                        <p>Selfie search is optional; visitors can browse galleries or use bib-number search instead. A person shown in a photograph can use the <a href="{{ route('photo-removal.create') }}">Photo Removal Request</a> process. For privacy questions or requests, <a href="{{ route('contact_us') }}">contact WivorPhotos</a>.</p>

                        <h2 class="h4 mt-4">Policy updates</h2>
                        <p class="mb-0">WivorPhotos may update this policy as the service changes. The date at the top identifies the current published version.</p>
                    </div>
                </div>
            </article>
        </div>
    </main>
@endsection
